version: "3.9"

services:
  mysql:
    image: mysql:8
    restart: "unless-stopped"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - '3306:3306'
    volumes:
      - ./dump-hibernate-final.sql:/docker-entrypoint-initdb.d/dump-hibernate-final.sql
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume: