version: "3.9"

services:
  mysql:
    image: mysql:8
    restart: "unless-stopped"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - '3306:3306'
    volumes:
      - ./dump-hibernate-final.sql:/docker-entrypoint-initdb.d/dump-hibernate-final.sql
      - mysql-volume:/var/lib/mysql

  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - '6379:6379'
      - '8001:8001'

volumes:
  mysql-volume: